[build]
  base = "spiroux-garde-meuble"
  command = "npm run build"
  publish = "spiroux-garde-meuble/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
